server:
  port : 8081
  error.include-message: always



# Redis Config
spring:
  application.name: todo
  jpa:
    show-sql: true
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate.ddl-auto: create-drop
  data:
    mongodb:
      host: localhost
      port: 27017
      database: myDB
    
todo:
  driverClassName: org.sqlite.JDBC
  url: jdbc:sqlite:memory:myDb
  username: sa 
  password: sa

